# Generated by Django 3.0.6 on 2020-05-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('pass_word', models.CharField(max_length=200)),
                ('type_user', models.IntegerField()),
            ],
            options={
                'ordering': ['user_name'],
            },
        ),
    ]
