# Generated by Django 3.0.6 on 2020-06-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courser', '0004_quests_id_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='point',
            field=models.CharField(default='Chưa kiểm tra', max_length=500),
        ),
    ]
